---
title: "Figure 3"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Figure 3}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
devtools::load_all()
library(tidyverse)
library(patchwork)
mytheme <-
  theme_bw() +
  theme(plot.tag = element_text(face = 'bold'))
```

```{r}
best_networks <-
  bind_rows(
    relu_net_last %>%
      filter(metric == 'error', split == 'val', hidden_dims <= 100) %>%
      group_by(init_seed, train_size) %>%
      summarise(error_rate = min(value)) %>%
      ungroup() %>%
      select(train_size, error_rate) %>%
      mutate(type = 'GD', name = 'GD'),
    relu_net_cp %>%
      filter(type == 'val', objective != 'gates_only') %>%
      group_by(init_seed, train_size, objective) %>%
      summarise(error_rate = min(error, na.rm = TRUE)) %>%
      ungroup() %>%
      select(train_size, error_rate, objective) %>%
      mutate(
        constraints = case_when(
          objective == 'hidden_layer' ~ 'Hidden Layer',
          objective == 'learned_contexts' ~ 'Learned Contexts',
          objective == 'random_contexts' ~ 'Random Contexts'
        ),
        type = paste0('SVM (', constraints, ')'),
        name = case_when(
          objective == 'hidden_layer' ~ 'SVM (HL)',
          objective == 'learned_contexts' ~ '(LC)',
          objective == 'random_contexts' ~ '(RC)'
        )
      ) %>%
      select(-objective, -constraints),
    deep_gln_cp %>%
      filter(type == 'val', constraints == 'implicit_bias', latent_dims <= 50, shatter_dims == 1) %>%
      group_by(context_seed, train_size) %>%
      summarise(error_rate = min(error)) %>%
      ungroup() %>%
      select(train_size, error_rate) %>%
      mutate(
        type = 'SVM (GLN)',
        name = '(GLN)'
      )
  ) %>%
  mutate(
    type = factor(type, levels = c('Best', 'GD', 'SVM (Hidden Layer)', 'SVM (Learned Contexts)', 'SVM (Random Contexts)', 'SVM (GLN)')),
    name = factor(name, levels = c('Best', 'GD', 'SVM (HL)', '(LC)', '(RC)', '(GLN)'))
  )
```

```{r}
p_a <- 
  best_networks %>%
  mutate(
    train_size = factor(train_size, levels = c('500', '1000', '2000'))
  ) %>%
  ggplot(aes(name, error_rate, fill = type, color = type, linetype = train_size, shape = train_size, group = train_size)) +
  stat_summary(geom = 'line', color = 'grey20', show.legend = FALSE) +
  stat_summary(geom = 'linerange', linetype = 'solid', show.legend = FALSE) +
  stat_summary(geom = 'point', show.legend = FALSE) +
  #facet_wrap(~train_size, ncol = 1, labeller = as_labeller(function(string) paste0('Training Size: ', string))) +
  scale_y_continuous(labels = scales::label_percent()) +
  labs(x = 'Training', y = 'Error on MNIST', color = '', fill = '') +
  scale_color_manual(values = c(viridisLite::viridis(4, end = 0.9, option = 'plasma'), 'grey20')) +
  mytheme +
  scale_linetype_manual(values = c(
    `500` = 'dotted',
    `1000` = 'dashed',
    `2000` = 'solid'
  ), name = 'Training Size') +
  labs(shape = 'Training Size')
p_a
```


```{r}
p_b <- 
  bind_rows(
  relu_net_last %>%
    filter(metric == 'error', split == 'val', momentum == 0.9, hidden_dims <= 100) %>%
    rename(error_rate = value) %>%
    select(-momentum, -metric, -init_seed, -split) %>%
    mutate(type = 'GD'),
  relu_net_cp %>%
    filter(momentum == 0.9, hidden_dims <= 100, type == 'val', objective != 'gates_only') %>%
    rename(error_rate = error) %>%
    select(-momentum, -init_seed, -type, -acc) %>%
    mutate(
      constraints = case_when(
        objective == 'hidden_layer' ~ 'Hidden Layer',
        objective == 'learned_contexts' ~ 'Learned Contexts',
        objective == 'random_contexts' ~ 'Random Contexts'
      ),
      type = paste0('SVM (', constraints, ')')
    )
) %>%
  mutate(
    train_size = factor(train_size, levels = c('500', '1000', '2000')),
    type = factor(type, levels = c('GD', 'SVM (Hidden Layer)', 'SVM (Learned Contexts)', 'SVM (Random Contexts)'))
  ) %>%
  ggplot(aes(hidden_dims, error_rate, color = type, linetype = train_size, shape = train_size)) +
  stat_summary(geom = 'linerange', show.legend = FALSE, linetype = 'solid') +
  stat_summary(geom = 'point') +
  stat_summary(geom = 'line') +
  #facet_wrap(~train_size, ncol = 1, labeller = as_labeller(function(string) paste0('Training size: ', string))) +
  scale_x_log10(name = 'Nr. of Hidden Units') +
  scale_color_viridis_d(
    labels = c(Last = 'GD', `infinite_time (architecture)` = 'Inf. (Architecture)', `infinite_time (implicit_bias)` = 'Inf. (Implicit Bias)'),
    name = 'Type of Network',
    end = 0.9,
    option = 'plasma'
  ) +
  scale_linetype_manual(values = c(
    `500` = 'dotted',
    `1000` = 'dashed',
    `2000` = 'solid'
  ), name = 'Training Size') +
  labs(shape = 'Training Size') +
  scale_y_continuous(labels = scales::percent_format(), name = 'Error on MNIST') +
  mytheme
p_b
```

```{r}
p_c <-
  relu_net_cp %>%
  filter(type == 'val', objective != 'gates_only') %>%
  rename(svm_error = error) %>%
  mutate(init_seed = as.numeric(init_seed), momentum = as.numeric(momentum)) %>%
  mutate(
    constraints = case_when(
      objective == 'hidden_layer' ~ 'Hidden Layer',
      objective == 'learned_contexts' ~ 'Learned Contexts',
      objective == 'random_contexts' ~ 'Random Contexts'
    ),
    type = paste0('Inf. (', constraints, ')')
  ) %>%
  inner_join(
    relu_net_last %>%
      filter(split == 'val', metric == 'error') %>%
      select(-split, -epoch) %>%
      rename(error = value),
    by = c('hidden_dims', 'train_size', 'init_seed', 'momentum')
  ) %>%
  filter(momentum == 0.9, hidden_dims <= 100) %>%
  mutate(
    train_size = factor(train_size, levels = c('500', '1000', '2000')),
    type = factor(type, levels = c('Last', 'Inf. (Hidden Layer)', 'Inf. (Learned Contexts)', 'Inf. (Random Contexts)'))
  ) %>%
  ggplot(aes(error, svm_error, color = type)) +
  geom_point(show.legend = FALSE) +
  geom_abline(slope = 1., intercept = 0., color = 'grey', size = 1) +
  scale_color_viridis_d(drop = FALSE, option = 'plasma', end = 0.9) +
  scale_x_continuous(labels = scales::percent_format(), name = 'GD-ReLU Error', breaks = c(0.05, 0.1, 0.15)) +
  scale_y_continuous(labels = scales::percent_format(), name = 'SVM Error') +
  coord_fixed() +
  mytheme
p_c
```

```{r}
p_d <-
  relu_net_cp %>%
  filter(type == 'comparison', objective != 'gates_only') %>%
  rename(inconsistency = error) %>%
  mutate(init_seed = as.numeric(init_seed), momentum = as.numeric(momentum)) %>%
  mutate(
    constraints = case_when(
      objective == 'hidden_layer' ~ 'Hidden Layer',
      objective == 'learned_contexts' ~ 'Learned Contexts',
      objective == 'random_contexts' ~ 'Random Contexts'
    ),
    type = paste0('Inf. (', constraints, ')')
  ) %>%
  inner_join(
    relu_net_last %>%
      filter(split == 'val', metric == 'error') %>%
      select(-split, -epoch) %>%
      rename(error = value),
    by = c('hidden_dims', 'train_size', 'init_seed', 'momentum')
  ) %>%
  filter(momentum == 0.9, hidden_dims <= 100) %>%
  mutate(
    train_size = factor(train_size, levels = c('500', '1000', '2000')),
    type = factor(type, levels = c('Fin.', 'Inf. (Hidden Layer)', 'Inf. (Learned Contexts)', 'Inf. (Random Contexts)'))
  ) %>%
  ggplot(aes(error, inconsistency, color = type)) +
  geom_point(show.legend = FALSE) +
  geom_function(fun = function(p) 1-(p*p+(1-p)*(1-p)), color = 'grey', size = 1) +
  scale_color_viridis_d(drop = FALSE, option = 'plasma', end = 0.9) +
  scale_x_continuous(labels = scales::percent_format(), name = 'GD-ReLU Error', breaks = c(0.05, 0.1, 0.15)) +
  scale_y_continuous(labels = scales::percent_format(), name = 'Inconsistency') +
  coord_fixed(ylim = c(NA, 0.175)) +
  mytheme
p_d
```

```{r}
p_c + p_d + p_a + p_b + 
  plot_layout(nrow = 1, guides = 'collect') +
  plot_annotation(tag_levels = 'a') &
  theme(legend.position = 'right', legend.direction = 'vertical') +
  theme(plot.margin = unit(c(0, 0, 0, 0), 'cm'))
ggsave('../figures/fig_3.pdf', width = 14, height = 4)
ggsave('../figures/fig_3.png', width = 14, height = 4)
```

```{r}
p_supp_a <- 
  bind_rows(
  relu_net_last %>%
    filter(metric == 'error', split == 'val', hidden_dims <= 100) %>%
    rename(error_rate = value) %>%
    select(-metric, -init_seed, -split) %>%
    mutate(type = 'GD'),
  relu_net_cp %>%
    filter(hidden_dims <= 100, type == 'val', objective != 'gates_only') %>%
    mutate(momentum = as.numeric(momentum)) %>%
    rename(error_rate = error) %>%
    select(-init_seed, -type, -acc) %>%
    mutate(
      constraints = case_when(
        objective == 'hidden_layer' ~ 'Hidden Layer',
        objective == 'learned_contexts' ~ 'Learned Contexts',
        objective == 'random_contexts' ~ 'Random Contexts'
      ),
      type = paste0('SVM (', constraints, ')')
    )
) %>%
  mutate(
    train_size = factor(train_size, levels = c('500', '1000', '2000')),
    type = factor(type, levels = c('GD', 'SVM (Hidden Layer)', 'SVM (Learned Contexts)', 'SVM (Random Contexts)')),
    momentum = if_else(momentum == 0., 'Momentum: 0', 'Momentum: 0.9')
  ) %>%
  ggplot(aes(hidden_dims, error_rate, color = type, linetype = train_size, shape = train_size)) +
  stat_summary(geom = 'linerange', show.legend = FALSE, linetype = 'solid') +
  stat_summary(geom = 'point') +
  stat_summary(geom = 'line') +
  #facet_wrap(~train_size, ncol = 1, labeller = as_labeller(function(string) paste0('Training size: ', string))) +
  scale_x_log10(name = 'Nr. of Hidden Units') +
  scale_color_viridis_d(
    labels = c(Last = 'GD', `infinite_time (architecture)` = 'Inf. (Architecture)', `infinite_time (implicit_bias)` = 'Inf. (Implicit Bias)'),
    name = 'Type of Network',
    end = 0.9,
    option = 'plasma'
  ) +
  scale_linetype_manual(values = c(
    `500` = 'dotted',
    `1000` = 'dashed',
    `2000` = 'solid'
  ), name = 'Training Size') +
  labs(shape = 'Training Size') +
  scale_y_continuous(labels = scales::percent_format(), name = 'Error on MNIST') +
  facet_grid(rows = vars(momentum)) +
  mytheme
p_supp_a
```

```{r}
p_supp_b <-
  relu_net_cp %>%
  filter(type == 'val', objective != 'gates_only') %>%
  rename(svm_error = error) %>%
  mutate(init_seed = as.numeric(init_seed), momentum = as.numeric(momentum)) %>%
  mutate(
    constraints = case_when(
      objective == 'hidden_layer' ~ 'Hidden Layer',
      objective == 'learned_contexts' ~ 'Learned Contexts',
      objective == 'random_contexts' ~ 'Random Contexts'
    ),
    type = paste0('Inf. (', constraints, ')')
  ) %>%
  inner_join(
    relu_net_last %>%
      filter(split == 'val', metric == 'error') %>%
      select(-split, -epoch) %>%
      rename(error = value),
    by = c('hidden_dims', 'train_size', 'init_seed', 'momentum')
  ) %>%
  filter(hidden_dims <= 100) %>%
  mutate(
    train_size = factor(train_size, levels = c('500', '1000', '2000')),
    type = factor(type, levels = c('Last', 'Inf. (Hidden Layer)', 'Inf. (Learned Contexts)', 'Inf. (Random Contexts)')),
    momentum = if_else(momentum == 0., 'Momentum: 0', 'Momentum: 0.9')
  ) %>%
  ggplot(aes(error, svm_error, color = type)) +
  geom_point(show.legend = FALSE) +
  geom_abline(slope = 1., intercept = 0., color = 'grey', size = 1) +
  scale_color_viridis_d(drop = FALSE, option = 'plasma', end = 0.9) +
  scale_x_continuous(labels = scales::percent_format(), name = 'GD-ReLU Error', breaks = c(0.05, 0.1, 0.15)) +
  scale_y_continuous(labels = scales::percent_format(), name = 'SVM Error') +
  coord_fixed() +
  facet_grid(rows = vars(momentum)) +
  mytheme
p_supp_b
```

```{r}
p_supp_c <-
  relu_net_cp %>%
  filter(type == 'comparison', objective != 'gates_only') %>%
  rename(inconsistency = error) %>%
  mutate(init_seed = as.numeric(init_seed), momentum = as.numeric(momentum)) %>%
  mutate(
    constraints = case_when(
      objective == 'hidden_layer' ~ 'Hidden Layer',
      objective == 'learned_contexts' ~ 'Learned Contexts',
      objective == 'random_contexts' ~ 'Random Contexts'
    ),
    type = paste0('Inf. (', constraints, ')')
  ) %>%
  inner_join(
    relu_net_last %>%
      filter(split == 'val', metric == 'error') %>%
      select(-split, -epoch) %>%
      rename(error = value),
    by = c('hidden_dims', 'train_size', 'init_seed', 'momentum')
  ) %>%
  filter(hidden_dims <= 100) %>%
  mutate(
    train_size = factor(train_size, levels = c('500', '1000', '2000')),
    type = factor(type, levels = c('Fin.', 'Inf. (Hidden Layer)', 'Inf. (Learned Contexts)', 'Inf. (Random Contexts)')),
    momentum = if_else(momentum == 0., 'Momentum: 0', 'Momentum: 0.9')
  ) %>%
  ggplot(aes(error, inconsistency, color = type)) +
  geom_point(show.legend = FALSE) +
  geom_function(fun = function(p) 1-(p*p+(1-p)*(1-p)), color = 'grey', size = 1) +
  scale_color_viridis_d(drop = FALSE, option = 'plasma', end = 0.9) +
  scale_x_continuous(labels = scales::percent_format(), name = 'GD-ReLU Error', breaks = c(0.05, 0.1, 0.15)) +
  scale_y_continuous(labels = scales::percent_format(), name = 'Inconsistency') +
  coord_fixed(ylim = c(NA, 0.175)) +
  facet_grid(rows = vars(momentum)) +
  mytheme
p_supp_c
```

```{r}
p_supp_b + p_supp_c + p_supp_a +
  #plot_layout(nrow = 1, guides = 'collect') +
  plot_annotation(tag_levels = 'a') &
  theme(legend.position = 'right', legend.direction = 'vertical')
ggsave('../figures/fig_3_supp.pdf', width = 14, height = 6)
```

